apiVersion: v1
kind: Service

metadata:
  name: excalidraw-service

spec:
  selector:
    app: excalidraw

  ports:
  - name: frontend
    port: 80
    targetPort: frontend
  - name: http-api
    port: 3000
    targetPort: http-api
  - name: websocket
    port: 8080
    targetPort: websocket

  type: LoadBalancer
